FROM ubuntu:latest

USER root

RUN apt-get update

RUN mkdir -p /opt/app

ENV PROJECT_HOME /opt/app

WORKDIR $PROJECT_HOME

ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz $PROJECT_HOME/

RUN tar -xvzf apache-tomcat-9.0.71.tar.gz

copy target/spring-boot-mongo-1.0.jar $PROJECT_HOME/spring-boot-mongo.jar

EXPOSE 8008

VOLUME /data/bd

CMD ["java" ,"-jar","./spring-boot-mongo.jar"]



